apiVersion: v1
kind: Service
metadata:
  name: rest-api
  namespace: rest-api
  labels:
    app: rest-api
spec:
  ports:
  - name: http   # Example name for the port, can be any descriptive name
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: rest-api
