apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rest-api
  name: rest-api
  namespace: rest-api 
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rest-api
status:
  loadBalancer: {}
